class Config:
    AUTHENTICATION_IP = ''
    ACCOUNTING_IP = ''

    KEYSTONE_URL = ''
    KEYSTONE_USERNAME = ''
    KEYSTONE_PASSWORD = ''
    KEYSTONE_PROJECT = ''
    KEYSTONE_ADMIN_PROJECT = ''
    KEYSTONE_SERVICE_PROJECT = ''
    KEYSTONE_USER_DOMAIN_NAME = ''
    KEYSTONE_PROJECT_DOMAIN_NAME = ''
