class Config:
    AUTHENTICATION_IP = ''
    ACCOUNTING_IP = ''

    AUTHORIZATION_POLICY_FILE = ''
    REDIS_EXPIRATION_TIME = ''
    AUTHORIZATION_USER_MARKER = ''
    AUTHORIZATION_ADMIN_MARKER = ''
    AUTHORIZATION_SERVICE_MARKER = ''

    KEYSTONE_URL = ''
    KEYSTONE_USERNAME = ''
    KEYSTONE_PASSWORD = ''
    KEYSTONE_PROJECT = ''
    KEYSTONE_ADMIN_PROJECT = ''
    KEYSTONE_SERVICE_PROJECT = ''
    KEYSTONE_USER_DOMAIN_NAME = ''
    KEYSTONE_PROJECT_DOMAIN_NAME = ''
