class Config:  
    AUTHENTICATION_IP = ''
    ACCOUNTING_IP = ''

    AUTHENTICATION_USERNAME = ''
    AUTHENTICATION_PASSWORD = ''

    AUTHORIZATION_POLICY_FILE = ''
    REDIS_URL = 'localhost'
    REDIS_PORT = 6379

    SERVICE_ROLE = 'admin'
    SERVICE_PROJECT = 'service'

    KEYSTONE_URL = ''
    KEYSTONE_USERNAME = ''
    KEYSTONE_PASSWORD = ''
    KEYSTONE_PROJECT = ''
    KEYSTONE_ADMIN_PROJECT = ''
    KEYSTONE_SERVICE_PROJECT = ''
    KEYSTONE_USER_DOMAIN_NAME = ''
    KEYSTONE_PROJECT_DOMAIN_NAME = ''

    AUTHORIZATION_TOKEN = None
